default_stages: [pre-commit]

default_language_version:
    python: python3.13

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
          - id: debug-statements
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: check-docstring-first
          - id: detect-private-key

    # Run the Ruff linter.
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.2
      hooks:
          # Linter
          - id: ruff
            types_or: [ python ]
            args: [--fix]
          # Formatter
          - id: ruff-format
            types_or: [ python ]

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
