name: Python Tests & Coverage Badge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # Important: This permission is required for the action to push the badge back to the repo.
  contents: write

jobs:
  test-and-update-badge:
    name: Run tests and update coverage badge
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests and generate coverage report
      run: |
        PYTHONPATH=. pytest --cov=is_goat_burning --cov-report=json

    - name: Generate coverage badge
      run: |
        coverage-badge -o coverage.svg

    - name: Commit and push coverage badge
      # This step only runs for pushes to the main branch, not for pull requests.
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add coverage.svg
        # Check if there are changes to commit
        git diff --staged --quiet || (git commit -m "ci: update coverage badge" && git push)
